org: harshclouddev
app: serverless-starter
service: aws-node-express-api-project
useDotenv: true

disabledDeprecations:
  - "*"

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  logs:
    httpApi: true

functions:
  api:
    handler: handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
